name: clang-format

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: './src'
        extensions: 'h,cpp'
        clangFormatVersion: 12
        style: file
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: Clang Robot
        author_email: robot@example.com
        message: 'style: clang-format llvm preset'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
